# Generated by Django 5.2.15 on 2026-06-26 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('SALES_REP', 'Sales Representative')], default='SALES_REP', max_length=20),
        ),
    ]
