# Generated by Django 5.2.15 on 2026-06-26 00:59

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator(message='Phone number must be in E.164-compatible format.', regex='^\\+?[1-9]\\d{7,14}$')])),
                ('website', models.URLField(blank=True)),
                ('customer_type', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('BUSINESS', 'Business')], default='BUSINESS', max_length=15)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('CHURNED', 'Churned')], default='ACTIVE', max_length=10)),
                ('source', models.CharField(choices=[('WEBSITE', 'Website'), ('REFERRAL', 'Referral'), ('CAMPAIGN', 'Campaign'), ('INBOUND', 'Inbound'), ('OUTBOUND', 'Outbound')], default='INBOUND', max_length=10)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('follow_up_type', models.CharField(choices=[('CALL', 'Call'), ('EMAIL', 'Email'), ('MEETING', 'Meeting'), ('TASK', 'Task'), ('DEMO', 'Demo')], max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('CANCELED', 'Canceled')], default='PENDING', max_length=10)),
                ('scheduled_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator(message='Phone number must be in E.164-compatible format.', regex='^\\+?[1-9]\\d{7,14}$')])),
                ('source', models.CharField(choices=[('WEBSITE', 'Website'), ('REFERRAL', 'Referral'), ('CAMPAIGN', 'Campaign'), ('INBOUND', 'Inbound'), ('OUTBOUND', 'Outbound')], default='INBOUND', max_length=10)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('CONTACTED', 'Contacted'), ('QUALIFIED', 'Qualified'), ('UNQUALIFIED', 'Unqualified'), ('CONVERTED', 'Converted'), ('LOST', 'Lost')], default='NEW', max_length=12)),
                ('estimated_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('stage', models.CharField(choices=[('DISCOVERY', 'Discovery'), ('QUALIFICATION', 'Qualification'), ('PROPOSAL', 'Proposal'), ('NEGOTIATION', 'Negotiation'), ('WON', 'Won'), ('LOST', 'Lost')], default='DISCOVERY', max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('probability', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('expected_close_date', models.DateField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
