# Generated by Django 5.2.15 on 2026-06-26 00:59

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='users.salesrepresentative'),
        ),
        migrations.AddField(
            model_name='followup',
            name='assigned_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='follow_ups', to='users.salesrepresentative'),
        ),
        migrations.AddField(
            model_name='followup',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_follow_ups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='followup',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='crm.customer'),
        ),
        migrations.AddField(
            model_name='lead',
            name='assigned_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='users.salesrepresentative'),
        ),
        migrations.AddField(
            model_name='lead',
            name='converted_customer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_lead', to='crm.customer'),
        ),
        migrations.AddField(
            model_name='lead',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_leads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='followup',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='crm.lead'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opportunities', to='crm.customer'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunities', to='crm.lead'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opportunities', to='users.salesrepresentative'),
        ),
        migrations.AddField(
            model_name='followup',
            name='opportunity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='crm.opportunity'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['name'], name='customer_name_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['status'], name='customer_status_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['owner', 'status'], name='customer_owner_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.CheckConstraint(condition=models.Q(('email', ''), ('phone_number', ''), _negated=True), name='customer_contact_required'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), condition=models.Q(('email', ''), _negated=True), name='customer_email_ci_unique'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['status'], name='lead_status_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['source'], name='lead_source_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['assigned_to', 'status'], name='lead_owner_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='lead',
            constraint=models.CheckConstraint(condition=models.Q(('email', ''), ('phone_number', ''), _negated=True), name='lead_contact_required'),
        ),
        migrations.AddConstraint(
            model_name='lead',
            constraint=models.CheckConstraint(condition=models.Q(('estimated_value__gte', 0)), name='lead_estimated_value_non_negative'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['stage'], name='opportunity_stage_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['owner', 'stage'], name='opportunity_owner_stage_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['customer', 'stage'], name='opportunity_customer_stage_idx'),
        ),
        migrations.AddConstraint(
            model_name='opportunity',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='opportunity_amount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='opportunity',
            constraint=models.CheckConstraint(condition=models.Q(('probability__gte', 0), ('probability__lte', 100)), name='opportunity_probability_range'),
        ),
        migrations.AddIndex(
            model_name='followup',
            index=models.Index(fields=['status', 'scheduled_at'], name='followup_status_scheduled_idx'),
        ),
        migrations.AddIndex(
            model_name='followup',
            index=models.Index(fields=['assigned_to', 'status'], name='followup_assignee_status_idx'),
        ),
        migrations.AddIndex(
            model_name='followup',
            index=models.Index(fields=['follow_up_type'], name='followup_type_idx'),
        ),
        migrations.AddConstraint(
            model_name='followup',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('customer__isnull', False), ('lead__isnull', True), ('opportunity__isnull', True)), models.Q(('customer__isnull', True), ('lead__isnull', False), ('opportunity__isnull', True)), models.Q(('customer__isnull', True), ('lead__isnull', True), ('opportunity__isnull', False)), _connector='OR'), name='followup_exactly_one_target'),
        ),
    ]
