# Generated by Django 5.2.15 on 2026-06-26 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_alter_lead_contact_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='stage',
            field=models.CharField(choices=[('QUALIFICATION', 'Qualification'), ('PROPOSAL', 'Proposal'), ('NEGOTIATION', 'Negotiation'), ('WON', 'Won'), ('LOST', 'Lost')], default='QUALIFICATION', max_length=15),
        ),
    ]
