from .base import *  # noqa: F403,F401

DEBUG = False
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
ALLOWED_HOSTS = ['crm-8fb5.onrender.com', 'localhost', '127.0.0.1']
